data(iris)
library(e1071)
f_0.1<-svm(Species~.,data = iris,type="c-classification",kernel="radial",cost=10,gamma=0.1)
summary(f_0.1)
p_0.1<-1predict(f_0.1,iris,decision.values=TRUE)
summary(p_0.1)
acc_0.1<-table(p_0.1,iris$Species)
classAgreement(acc_0.1)
plot(f_0.1,iris,petal.Width~petal.Length,slice=list(sepal.Width=3,Sepal.Length=4))
